# Generated by Django 3.2.25 on 2024-08-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisementmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('addcat', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='add_images/')),
            ],
            options={
                'db_table': 'advertisementmodel',
            },
        ),
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('addcat', models.TextField()),
                ('desc', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'productmodel',
            },
        ),
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usermodel',
            },
        ),
    ]
