# Generated by Django 3.2.25 on 2024-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='post_url',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='addcat',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='name',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
